server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
#    是eureka-server且是集群部署才需要设置为true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/