// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package com.example.grpc.gencode;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.gencode.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string firstName = 1;</code>
   */
  boolean hasFirstName();
  /**
   * <code>required string firstName = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>required string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>required string lastName = 2;</code>
   */
  boolean hasLastName();
  /**
   * <code>required string lastName = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>required string lastName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
